(package "tspew"
         "0.1.0"
         "Clean and format \"template spew\" errors from gcc and Clang")

(website-url "https://github.com/jefftrull/tspew")
(keywords "c")

(package-file "tspew.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.1")
(depends-on "compat")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
